[build-system]
requires = ["setuptools", "wheel"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "spotipy"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "spotipy.*"
ignore_missing_imports = true