apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-service
  name: test-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30001
  selector:
    app: test
  type: NodePort
status:
  loadBalancer: {}
